server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/spring-oauth
          jwk-set-uri: http://localhost:8080/auth/realms/spring-oauth/protocol/openid-connect/certs
